export enum ReloadActionEnum {
  RELOAD_UNIQUE_ITEM_QUANTITY = 'RELOAD_UNIQUE_ITEM_QUANTITY',
  RELOAD_SELL_ENDED_TRANSACTION_LIST = 'RELOAD_SELL_ENDED_TRANSACTION_LIST',
  RELOAD_SELL_PROGRESS_TRANSACTION_LIST = 'RELOAD_SELL_PROGRESS_TRANSACTION_LIST',
  RELOAD_BUY_TRANSACTION_LIST = 'RELOAD_BUY_TRANSACTION_LIST',
}
