'use client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '../styles/global.css';
import '../styles/theme.scss';
import Provider from './provider';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by David M',
// };

const queryClient = new QueryClient();

function RootLayout({ children }: IChildren): React.ReactElement {
  return (
    <html lang='fr'>
      <body>
        <Provider>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;
