import Provider from './provider.client';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by David M',
};

function RootLayout({ children }: IChildren) {
  return (
    <html lang='fr'>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}

export default RootLayout;
